### PR TITLE
fix(angular): fix styles and behavior of form inputs in readonly mode

### LINKED ISSUE #916: Bug: Date widget - wrong behaviour in read-only state
**Describe the bug**
Date widget behaves wrongly when in read-only state. 
Compare specification with screenshot below.
Spec = https://digital.sbb.ch/en/webapps/components/datepicker 

**Expected behavior**
image

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome and others

**Additional context**
Problembeschreibung, die ich an Franco Ehrat gesandt habe:
Date Widget:
•	Lässt sich trotz «read-only» Status öffnen und ein anderes Datum auswählen.
•	Das neue Datum (z.B. 6. Nov. 2021) wird ins Feld übernommen.
•	(kann aber natürlich nicht gespeichert werden, da unsere Applikation im Read-only-Mode keinen Speichern-Button anbietet)

Antwort von Franco Ehrat:
•	Date Widget: absolut einverstanden. Das Verhalten stimmt da noch nicht mit der UX Spezifikation überein. --> Bug

### LINKED ISSUE #917: Bug: Select (Dropdown) widget - wrong behaviour in read-only state
**Describe the bug**
Select (Dropdown) widget behaves wrongly when in read-only state.
Compare specification with screenshot below.
Spec = https://digital.sbb.ch/en/webapps/components/select

**Expected behavior**
image

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome and others

**Additional context**
Problembeschreibung, die ich an Franco Ehrat gesandt habe:
Dropdown-Felder (Select Menu)
•	werden noch mit Rahmen angezeigt
•	werden noch mit grauer Füllung (Hintergrund) angezeigt
•	Dropdown-Pfeil am rechten Feld-Ende wird noch angezeigt, kann aber nicht gedrückt/geöffnet werden

Antwort von Franco Ehrat:
•	Dropdown / Select: das gleiche wie beim Date Widget. Die UX Spezifikation ist auch hier noch nicht eingehalten. --> Bug

### LINKED ISSUE #918: Bug: Placeholder-texts - wrong behaviour in read-only state
**Describe the bug**
Placeholder-texts of various UI elements are still shown when in read-only state. 

**Expected behavior**
Placeholder-texts shall not be displayed. Rather showing a single "-" as recommended by Franco Ehrat (see below, additional context).
image

**Screenshots**
Bug state: 
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome and others

**Additional context**
Problembeschreibung, die ich an Franco Ehrat gesandt habe:
Placeholder-Texte 
•	Placeholder-Texte werden angezeigt
•	macht keinen Sinn, sollten in allen Text-Widgets im «read-only» Status unterdrückt werden

Antwort von Franco Ehrat:
•	Placeholder: da bin ich auch bei dir. Das hatte ich mir bisher gar nicht überlegt. Ich würde vorschlagen, dass man in diesem Fall nicht einfach gar nichts anzeigt, sondern vielleicht einen Bindestrich.

### PR DESCRIPTION
**Pull request by jeripeierSBB**
Closes #916 
Closes #917 
Closes #918

### CODE REVIEW

File: src/angular/datepicker/datepicker/datepicker.ts [hunk 1]
```diff
@@ -138,6 +138,10 @@ export class SbbDatepicker<D> implements OnDestroy {
   }
   private _arrows = false;
 
+  get arrowsVisible() {
```
Comment (kyubisation) [inline src/angular/datepicker/datepicker/datepicker.ts:141]: Maybe document these properties?

File: src/angular/input/input.ts [hunk 2]
```diff
@@ -66,7 +66,8 @@ const _SbbInputBase = mixinErrorState(
     // state usually overlaps with `aria-required` when the input is empty and can be redundant.
     '[attr.aria-invalid]': '(empty && required) ? null : errorState',
     '[attr.aria-required]': 'required',
-    '[attr.placeholder]': 'placeholder || null',
+    '[attr.placeholder]': `!readonly ? placeholder || null : '-'`,
```
Comment (kyubisation) [inline src/angular/input/input.ts:69]:
```suggestion
    '[attr.placeholder]': `!readonly ? (placeholder || null) : '-'`,
```
This is easier to read to me. What do you think?

File: src/angular/select/select/select.html [hunk 3]
```diff
@@ -4,7 +4,9 @@
   class="sbb-select-value"
   [class.sbb-select-value-empty]="empty"
 >
-  <span *ngSwitchCase="true" class="sbb-select-placeholder">{{ placeholder || '\u00A0' }}</span>
+  <span *ngSwitchCase="true" class="sbb-select-placeholder"
+    >{{ !readonly ? placeholder || '\u00A0': '-' }}</span
```
Comment (kyubisation) [inline src/angular/select/select/select.html:8]:
```suggestion
    >{{ !readonly ? (placeholder || '\u00A0') : '-' }}</span
```

File: src/components-examples/angular/datepicker/datepicker-simple-reactive/datepicker-simple-reactive-example.html [hunk 4]
```diff
@@ -14,6 +14,7 @@
       [max]="maxDate.value"
       (dateChange)="dateChangeEvent($event)"
       (dateInput)="dateInputEvent($event)"
+      [readonly]="readonly.value"
```
Comment (kyubisation) [inline src/components-examples/angular/datepicker/datepicker-simple-reactive/datepicker-simple-reactive-example.html:17]: I'd recommend to move this to above the event listeners

**Review by kyubisation — CHANGES_REQUESTED** [review]

File: src/angular/datepicker/datepicker/datepicker.ts [hunk 5]
```diff
@@ -138,6 +138,11 @@ export class SbbDatepicker<D> implements OnDestroy {
   }
   private _arrows = false;
 
+  /** Whether arrows should be shown */
```
Comment (kyubisation) [inline src/angular/datepicker/datepicker/datepicker.ts:141]:
```suggestion
  /** Whether arrows should be shown. */
```

File: src/angular/datepicker/datepicker/datepicker.ts [hunk 6]
```diff
@@ -148,6 +153,11 @@ export class SbbDatepicker<D> implements OnDestroy {
   }
   private _toggle = true;
 
+  /** Whether the toggle should be shown */
```
Comment (kyubisation) [inline src/angular/datepicker/datepicker/datepicker.ts:156]:
```suggestion
  /** Whether the toggle should be shown. */
```

**Review by kyubisation — APPROVED** [review]
LGTM 👍 
Missing dots 😄
