### PR TITLE
fix(angular/lightbox): fix height calculation on mobile

### LINKED ISSUE #1586: Bug: Lightbox Buttons bugged on mobile devices
**Describe the bug**
When testing our application with mobile devices we discovered that lightbox action buttons are not or just partly visible/cut off. To exclude that this is app specific, we tested the examples at angular.app.sbb.ch and have seen the issues.
Besides the cutoff it seems that the button positioning on lightbox with confirmation is also not optimised - dont know if this is relevant for this bug.

**To Reproduce**
1. Grab your mobile
2. go to https://angular.app.sbb.ch/angular/components/lightbox/examples
3. test any lightbox
4. See cutoff and co

**Screenshots**

iphone
android_sony
android_sony confirm

**Smartphone (please complete the following information):**
 - Device: iPhone and Sony with Android

### PR DESCRIPTION
**Pull request by mhaertwig**
Use `window.innerHeight` instead of `100vh` to calculate the height of the `SbbLightBox`.  This is necessary because on mobile Chrome and Safari, `100vh` includes the address bar and is therefore taller than the actual viewport (see e.g. [this explanation](https://bugs.webkit.org/show_bug.cgi?id=141832#c5)). This led to cut off buttons in the lightbox.

Closes #1586

### CODE REVIEW

File: src/angular/lightbox/lightbox-container.ts [hunk 1]
```diff
@@ -64,6 +66,11 @@ export class SbbLightboxContainer extends _SbbDialogContainerBase {
     }
   }
 
+  @HostListener('window:resize', ['$event'])
```
Comment (kyubisation) [inline src/angular/lightbox/lightbox-container.ts:69]: Ideally we could use the ScrollDispatcher from the CDK here, but this should work.

File: src/angular/lightbox/lightbox-container.ts [hunk 2]
```diff
@@ -64,6 +66,11 @@ export class SbbLightboxContainer extends _SbbDialogContainerBase {
...
+  onResize() {
```
Comment (kyubisation) [inline src/angular/lightbox/lightbox-container.ts:70]: Nitpick
```suggestion
  _handleResize() {
```

File: src/angular/lightbox/lightbox-container.ts [hunk 3]
```diff
@@ -95,4 +104,8 @@ export class SbbLightboxContainer extends _SbbDialogContainerBase {
       focusMonitor
     );
   }
+
+  ngOnInit(): void {
+    this._innerHeight = window.innerHeight;
```
Comment (kyubisation) [inline src/angular/lightbox/lightbox-container.ts:109]: This would break server side rendering, where the window (or document) object might not be available.
See e.g. https://github.com/sbb-design-systems/sbb-angular/blob/main/src/angular/autocomplete/autocomplete-trigger.ts#L300-L304

File: src/angular/lightbox/lightbox-container.ts [hunk 4]
```diff
@@ -95,4 +104,8 @@ export class SbbLightboxContainer extends _SbbDialogContainerBase {
       focusMonitor
     );
   }
+
+  ngOnInit(): void {
```
Comment (kyubisation) [inline src/angular/lightbox/lightbox-container.ts:108]: Could this not be calculated in the constructor?

**Review by kyubisation — CHANGES_REQUESTED** [review]
Thank you for your work 👍

File: src/angular/lightbox/lightbox-container.ts (hunk 1 above)
Comment (mhaertwig) [reply src/angular/lightbox/lightbox-container.ts]: I've used the `ViewportRuler`.

File: src/angular/lightbox/lightbox-container.ts [hunk 5]
```diff
@@ -82,6 +89,7 @@ export class SbbLightboxContainer extends _SbbDialogContainerBase {
     ngZone: NgZone,
     overlayRef: OverlayRef,
     private _changeDetectorRef: ChangeDetectorRef,
+    private _viewportRuler: ViewportRuler,
```
Comment (mhaertwig) [inline src/angular/lightbox/lightbox-container.ts:92]: Seems like nobody is using the `SbbLightboxContainer` directly. Should we mark it as breaking change anyways?

**Review by kyubisation — APPROVED** [review]
LGTM 👍

**Review by jeripeierSBB — APPROVED** [review]
LGTM
