### PR TITLE
fix: correct focus of textarea and resizing behaviour

### LINKED ISSUE #194: Bug: sbb-textarea doesn't support bigger height correctly
**Describe the bug**
When sbb-textarea size is bigger than one line, only click on first line activate it.
In addition, saving such resized field and opening it results in only first line of field visible.

**Expected behavior**
Clicking anywhere in textarea activate it.
Multiple lines of text are visible after save.

**Screenshots**
textarea

### PR DESCRIPTION
**Pull request by jeripeierSBB**
Closes #194

### CODE REVIEW

File: projects/sbb-esta/angular-public/textarea/src/textarea/textarea.component.ts [hunk 1]
```diff
@@ -113,26 +192,100 @@ export class TextareaComponent implements ControlValueAccessor {
...
+          this.autosize.resizeToFitContent(true);
+        });
+    });
+  }
+
+  /**
+   * @docs-private
+   */
+  ngDoCheck() {
+    this.triggerResize();
```
Comment (kyubisation) [inline projects/sbb-esta/angular-public/textarea/src/textarea/textarea.component.ts]: Maybe explain why this is necessary
