### PR TITLE
fix(angular/tooltip): fix displaying close icon if click trigger was used

### LINKED ISSUE #1050: Bug: tooltip with template and trigger "click" is missing close button
**Describe the bug**
when creating a tooltip with a template and the trigger "click" there is no close button:
image

### PR DESCRIPTION
**Pull request by jeripeierSBB**
Closes #1050

### CODE REVIEW

File: src/angular/tooltip/tooltip.ts [hunk 1]
```diff
@@ -818,6 +820,9 @@ export abstract class _TooltipComponentBase implements OnDestroy {
   /** Subject for notifying that the tooltip has been hidden from the view */
   private readonly _onHide: Subject<void> = new Subject<void>();
 
+  /** Whether the tooltip component was triggered by click */
+  triggeredByClick: boolean = false;
```
Comment (kyubisation) [inline src/angular/tooltip/tooltip.ts:824]: This should be prefixed with _

**Review by kyubisation — CHANGES_REQUESTED** [review]

**Review by kyubisation — APPROVED** [review]
LGTM 👍
