### PR TITLE
fix: remove outline from tab content

### LINKED ISSUE #610: Bug: Chromium based browsers outlines content of tabs by clicking
**Describe the bug**
In chromium based Browsers the contents of the tabs component are outlined 
when clicking anywhere inside the tabs component element. The behaviour occurs only in chromium based Browser (Chrome, Edge (Chromium), Vivaldi...). Does not occur in other Browsers (Firefox, IE). 

**To Reproduce**
1. Go with chrome to 'https://sbb-angular.app.sbb.ch/business/components/tabs'
2. Go to 'Examples'
3. Click on 'Content 1' element

**Expected behavior**
Elements inside the Tab component should not get outlined

**Screenshots**
chromium_bug_tabs_component

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chromium based (Chrome, Edge (Chromium), Vivaldi etc.)

### PR DESCRIPTION
**Pull request by jeripeierSBB**
Closes #610

### CODE REVIEW

File: src/angular-public/tabs/tab/tab.component.ts [hunk 1]
```diff
@@ -25,39 +24,43 @@ let counter = 0;
   selector: 'sbb-tab',
   templateUrl: './tab.component.html',
   changeDetection: ChangeDetectionStrategy.OnPush,
+  host: {
+    'attr.role': 'tabpanel',
```
Comment (kyubisation) [inline src/angular-public/tabs/tab/tab.component.ts:28]:
```suggestion
    role: 'tabpanel',
```

**Review by kyubisation — APPROVED** [review]
LGTM 👍 
One minor suggestion

File: src/angular-public/tabs/tabs/tabs.component.ts [hunk 2]
```diff
@@ -26,10 +25,17 @@ let counter = 0;
...
+  host: {
+    class: 'sbb-tabs',
+  },
 })
 export class TabsComponent implements AfterContentInit, OnDestroy {
-  /** @docs-private */
-  @HostBinding('class.sbb-tabs') _tabsClass = true;
+  /**
+   * @docs-private
+   *  @deprecated internal detail
```
Comment (jeripeierSBB) [inline src/angular-public/tabs/tabs/tabs.component.ts:35]:
```suggestion
   * @deprecated internal detail
```
