### PR TITLE
fix: scroll to active option in autocomplete and select

### LINKED ISSUE #723: Bug: The options list within an sbb-select component is not scrolled down to the previously selected option
**Describe the bug**
The behavior of the `sbb-select` component has been changed in the new version (11.2.0). When opening a long options list, it is not scrolled down to the selected item anymore (which is important for our use case). 

**To Reproduce**
1. Go to https://angular-umr8r6.stackblitz.io/
2. Click on the select element.
3. Notice that the options list is not scrolled down to the selected element (50).

**Expected behavior**
The previously selected option should appear when clicking on the select element, as it was in version 10.3.2.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 88.0.4324.150

### PR DESCRIPTION
**Pull request by jeripeierSBB**
Closes #723

### CODE REVIEW

File: src/angular-public/autocomplete/autocomplete/autocomplete-trigger.directive.ts [hunk 1]
```diff
@@ -445,14 +498,12 @@ export class SbbAutocompleteTrigger implements ControlValueAccessor, AfterViewIn
...
       this._inputValue.next(target.value);
 
-      if (this._canOpen() && document.activeElement === event.target) {
+      if (this._canOpen() && this._document.activeElement === event.target) {
         this.openPanel();
       }
     }
   }
 
-  // Note: we use `focusin`, as opposed to `focus`, in order to open the panel
```
Comment (kyubisation) [inline src/angular-public/autocomplete/autocomplete/autocomplete-trigger.directive.ts:454]: Why did you remove the comment

File: src/angular-public/autocomplete/autocomplete/autocomplete-trigger.directive.ts [hunk 2]
```diff
@@ -693,37 +712,60 @@ export class SbbAutocompleteTrigger implements ControlValueAccessor, AfterViewIn
       positionStrategy: this._getOverlayPosition(),
       scrollStrategy: this._scrollStrategy(),
       width: this._getPanelWidth(),
-      panelClass: 'sbb-overlay-panel',
+      panelClass: this._defaults?.overlayPanelClass,
```
Comment (kyubisation) [inline src/angular-public/autocomplete/autocomplete/autocomplete-trigger.directive.ts:715]: Should we not ensure 'sbb-overlay-panel' is set?
